name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
  push: {branches: ["master", "main"]}

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          
          user: ar-ilyes
          template: classic
          
          config_include_private: yes
          
          base: header, activity, community, repositories, metadata
          
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          
          filename: metrics.plugin.isocalendar.svg
          config_timezone: Europe/Paris
